/**:
  ros__parameters:
    mapper:
      localization_mode: 0
      depth_image_topic: RealSense_Camera/depth
      point_cloud_topic: livox/lidar
      pose_topic: self_localization/pose
      odom_topic: sensor_measurements/odom
      map_frame_id : drone0/odom

      robot_size: [0.3, 0.3, 0.1]

      depth_intrinsics: [606.3120727539062, 605.92626953125, 314.6913146972656, 252.1909942626953]
      depth_scale_factor: 1000.0
      depth_min_value: 0.5
      depth_max_value: 5.0
      depth_filter_margin: 2
      depth_skip_pixel: 2
      image_cols: 640
      image_rows: 480
      body_to_depth_sensor: [0.0, 0.0, 1.0, 0.13,
                             -1.0, 0.0, 0.0, 0.0,
                             0.0, -1.0, 0.0, -0.022,
                             0.0, 0.0, 0.0, 1.0]

      pointcloud_min_distance: 0.5
      pointcloud_max_distance: 5.0
      body_to_pointcloud_sensor: [0.7071068, 0.0000000, 0.7071068, 0.0795,
                                  0.0000000, 1.0000000, 0.0000000, 0.0,
                                  -0.7071068, 0.0000000, 0.7071068, 0.0323,
                                  0.0, 0.0, 0.0, 1.0]

      raycast_max_length: 5.0
      p_hit: 0.70
      p_miss: 0.35
      p_min: 0.12
      p_max: 0.97
      p_occ: 0.80

      map_resolution: 0.1
      ground_height: -0.1
      map_size: [160.0, 160.0, 10.0]
      local_update_range: [5.0, 5.0, 5.0]
      local_bound_inflation: 3.0
      clean_local_map: false

      local_map_size: [5.0, 5.0, 10.0]
      max_height_visualization: 4.0
      visualize_global_map: true
      verbose: false

      prebuilt_map_directory: "No"
