/**:
  ros__parameters:
    drone_namespace: drone0
    takeoff_height: 1.0 # m
    frame_id: drone0/map
    odom_topic: /drone0/sensor_measurements/odom
    wait_for_topics_ready: false
    takeoff_wait_timeout_sec: 8.0
    require_takeoff_feedback: false
    circle_radius: 0.75 # m
    time_to_max_radius: 20 #s
    velocity: 0.5 #m/s
    yaw_control: false