/**:
  ros__parameters:
    takeoff_height: 1.0 # m
    frame_id: drone0/map
    odom_topic: /drone0/sensor_measurements/odom
    
    wait_for_topics_ready: false
    takeoff_wait_timeout_sec: 8.0
    require_takeoff_feedback: false
    desired_velocity: 1.0 # m/s
    desired_acceleration: 1.0 # m/s^2
    desired_angular_velocity: 0.5 # rad/s
    replan_time_for_dynamic_obstacles: 0.3
