/**:
  ros__parameters:
    color_image_topic: /camera/color/image_raw
    time_step: 0.0
    debug_visualization: True
    use_gpu: True
    conf_threshold: 0.35
    iou_threshold: 0.45
    target_classes: ["person"]
    model_path: ""
    labels_path: ""
